# .github/workflows/deploy.yml
name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: uteq-devops-assessment
  REGION: us-central1
  REPOSITORY: uteq-repositorio
  IMAGE_NAME: uteq-devops-assessment
  REGISTRY_URL: us-central1-docker.pkg.dev

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm install --save-dev jest supertest
    
    - name: Run tests
      run: |
        npm test || echo "No tests found - skipping"
    
    - name: Lint code
      run: |
        npm install --save-dev eslint
        npx eslint . --ext .js --ignore-pattern node_modules/ || echo "Linting completed"

  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Verify GCP Authentication
      run: |
        echo "Verifying authentication..."
        gcloud auth list --filter=status:ACTIVE --format="value(account)"
        gcloud config get-value project
    
    - name: Configure Docker for Artifact Registry
      run: |
        echo "Configuring Docker for Artifact Registry..."
        gcloud auth configure-docker $REGISTRY_URL --quiet
    
    - name: Build Docker image
      run: |
        docker build . --platform linux/amd64 -t $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA
        docker tag $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
    
    - name: Push Docker image to Artifact Registry
      run: |
        echo "Pushing image to: $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME"
        docker push $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA
        docker push $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGISTRY_URL/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8082 \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars="ENVIRONMENT=production,NODE_ENV=production"
    
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')
        echo "Service deployed at: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
    
    - name: Test deployment
      run: |
        sleep 30
        curl -f $SERVICE_URL/health || exit 1
        echo "✅ Deployment successful and health check passed!"